// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"
#include "Microsoft.UI.Composition.h"
#include "Microsoft.UI.Xaml.h"
#include "Microsoft.UI.Xaml.Controls.h"
#include "Microsoft.UI.Xaml.Controls.Primitives.h"
#include "Microsoft.UI.Xaml.Media.h"
#include "Windows.UI.h"
#include "XamlToolkit.WinUI.h"
#include "XamlToolkit.WinUI.Controls.h"

/* Forward Declarations */
#ifndef ____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider_FWD_DEFINED__
#define ____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider_FWD_DEFINED__
    typedef interface __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider;

#endif // ____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider_FWD_DEFINED__

#ifndef ____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics_FWD_DEFINED__
#define ____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics_FWD_DEFINED__
    typedef interface __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics;

#endif // ____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics_FWD_DEFINED__

#ifndef ____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer_FWD_DEFINED__
#define ____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer_FWD_DEFINED__
    typedef interface __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer;

#endif // ____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer_FWD_DEFINED__

#ifndef ____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerStatics_FWD_DEFINED__
#define ____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerStatics_FWD_DEFINED__
    typedef interface __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerStatics __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerStatics;

#endif // ____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerStatics_FWD_DEFINED__

// Parameterized interface forward declarations (C)

// Collection interface definitions

typedef struct __x_ABI_CXamlToolkit_CWinUI_CHsvColor __x_ABI_CXamlToolkit_CWinUI_CHsvColor;

#if !defined(____x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHsvColor_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHsvColor_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHsvColor __x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHsvColor;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHsvColor;

    typedef struct __x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHsvColorVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHsvColor* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHsvColor* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHsvColor* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHsvColor* This,
        IInspectable* sender,
        struct __x_ABI_CXamlToolkit_CWinUI_CHsvColor args);

        END_INTERFACE
    } __x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHsvColorVtbl;

    interface __x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHsvColor
    {
        CONST_VTBL struct __x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHsvColorVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHsvColor_INTERFACE_DEFINED__
    
#ifndef ____x_ABI_CMicrosoft_CUI_CComposition_CIAnimationObject_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CComposition_CIAnimationObject_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CComposition_CIAnimationObject __x_ABI_CMicrosoft_CUI_CComposition_CIAnimationObject;

#endif // ____x_ABI_CMicrosoft_CUI_CComposition_CIAnimationObject_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CUI_CComposition_CIVisualElement_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CComposition_CIVisualElement_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CComposition_CIVisualElement __x_ABI_CMicrosoft_CUI_CComposition_CIVisualElement;

#endif // ____x_ABI_CMicrosoft_CUI_CComposition_CIVisualElement_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CUI_CComposition_CIVisualElement2_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CComposition_CIVisualElement2_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CComposition_CIVisualElement2 __x_ABI_CMicrosoft_CUI_CComposition_CIVisualElement2;

#endif // ____x_ABI_CMicrosoft_CUI_CComposition_CIVisualElement2_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CIControl_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CIControl_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CXaml_CControls_CIControl __x_ABI_CMicrosoft_CUI_CXaml_CControls_CIControl;

#endif // ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CIControl_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CIControlOverrides_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CIControlOverrides_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CXaml_CControls_CIControlOverrides __x_ABI_CMicrosoft_CUI_CXaml_CControls_CIControlOverrides;

#endif // ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CIControlOverrides_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CIControlProtected_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CIControlProtected_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CXaml_CControls_CIControlProtected __x_ABI_CMicrosoft_CUI_CXaml_CControls_CIControlProtected;

#endif // ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CIControlProtected_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CISlider_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CISlider_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CXaml_CControls_CISlider __x_ABI_CMicrosoft_CUI_CXaml_CControls_CISlider;

#endif // ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CISlider_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CPrimitives_CIRangeBase_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CPrimitives_CIRangeBase_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CXaml_CControls_CPrimitives_CIRangeBase __x_ABI_CMicrosoft_CUI_CXaml_CControls_CPrimitives_CIRangeBase;

#endif // ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CPrimitives_CIRangeBase_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CPrimitives_CIRangeBaseOverrides_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CPrimitives_CIRangeBaseOverrides_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CXaml_CControls_CPrimitives_CIRangeBaseOverrides __x_ABI_CMicrosoft_CUI_CXaml_CControls_CPrimitives_CIRangeBaseOverrides;

#endif // ____x_ABI_CMicrosoft_CUI_CXaml_CControls_CPrimitives_CIRangeBaseOverrides_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty __x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty;

#endif // ____x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CUI_CXaml_CIDependencyObject_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CXaml_CIDependencyObject_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CXaml_CIDependencyObject __x_ABI_CMicrosoft_CUI_CXaml_CIDependencyObject;

#endif // ____x_ABI_CMicrosoft_CUI_CXaml_CIDependencyObject_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CUI_CXaml_CIFrameworkElement_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CXaml_CIFrameworkElement_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CXaml_CIFrameworkElement __x_ABI_CMicrosoft_CUI_CXaml_CIFrameworkElement;

#endif // ____x_ABI_CMicrosoft_CUI_CXaml_CIFrameworkElement_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CUI_CXaml_CIFrameworkElementOverrides_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CXaml_CIFrameworkElementOverrides_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CXaml_CIFrameworkElementOverrides __x_ABI_CMicrosoft_CUI_CXaml_CIFrameworkElementOverrides;

#endif // ____x_ABI_CMicrosoft_CUI_CXaml_CIFrameworkElementOverrides_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CUI_CXaml_CIFrameworkElementProtected_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CXaml_CIFrameworkElementProtected_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CXaml_CIFrameworkElementProtected __x_ABI_CMicrosoft_CUI_CXaml_CIFrameworkElementProtected;

#endif // ____x_ABI_CMicrosoft_CUI_CXaml_CIFrameworkElementProtected_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CUI_CXaml_CIUIElement_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CXaml_CIUIElement_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CXaml_CIUIElement __x_ABI_CMicrosoft_CUI_CXaml_CIUIElement;

#endif // ____x_ABI_CMicrosoft_CUI_CXaml_CIUIElement_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CUI_CXaml_CIUIElementOverrides_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CXaml_CIUIElementOverrides_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CXaml_CIUIElementOverrides __x_ABI_CMicrosoft_CUI_CXaml_CIUIElementOverrides;

#endif // ____x_ABI_CMicrosoft_CUI_CXaml_CIUIElementOverrides_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CUI_CXaml_CIUIElementProtected_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CXaml_CIUIElementProtected_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CXaml_CIUIElementProtected __x_ABI_CMicrosoft_CUI_CXaml_CIUIElementProtected;

#endif // ____x_ABI_CMicrosoft_CUI_CXaml_CIUIElementProtected_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CUI_CXaml_CMedia_CIBrush_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CXaml_CMedia_CIBrush_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CXaml_CMedia_CIBrush __x_ABI_CMicrosoft_CUI_CXaml_CMedia_CIBrush;

#endif // ____x_ABI_CMicrosoft_CUI_CXaml_CMedia_CIBrush_FWD_DEFINED__

typedef struct __x_ABI_CWindows_CUI_CColor __x_ABI_CWindows_CUI_CColor;

typedef enum __x_ABI_CXamlToolkit_CWinUI_CControls_CColorChannel __x_ABI_CXamlToolkit_CWinUI_CControls_CColorChannel;

typedef enum __x_ABI_CXamlToolkit_CWinUI_CControls_CColorRepresentation __x_ABI_CXamlToolkit_CWinUI_CControls_CColorRepresentation;

#if !defined(____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider_INTERFACE_DEFINED__)
    #define ____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider_INTERFACE_DEFINED__
    typedef struct __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Color)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
        struct __x_ABI_CWindows_CUI_CColor* value);
    HRESULT (STDMETHODCALLTYPE* put_Color)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
        struct __x_ABI_CWindows_CUI_CColor value);
    HRESULT (STDMETHODCALLTYPE* get_ColorChannel)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
        enum __x_ABI_CXamlToolkit_CWinUI_CControls_CColorChannel* value);
    HRESULT (STDMETHODCALLTYPE* put_ColorChannel)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
        enum __x_ABI_CXamlToolkit_CWinUI_CControls_CColorChannel value);
    HRESULT (STDMETHODCALLTYPE* get_ColorRepresentation)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
        enum __x_ABI_CXamlToolkit_CWinUI_CControls_CColorRepresentation* value);
    HRESULT (STDMETHODCALLTYPE* put_ColorRepresentation)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
        enum __x_ABI_CXamlToolkit_CWinUI_CControls_CColorRepresentation value);
    HRESULT (STDMETHODCALLTYPE* get_DefaultForeground)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
        __x_ABI_CMicrosoft_CUI_CXaml_CMedia_CIBrush** value);
    HRESULT (STDMETHODCALLTYPE* put_DefaultForeground)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
        __x_ABI_CMicrosoft_CUI_CXaml_CMedia_CIBrush* value);
    HRESULT (STDMETHODCALLTYPE* get_HsvColor)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
        struct __x_ABI_CXamlToolkit_CWinUI_CHsvColor* value);
    HRESULT (STDMETHODCALLTYPE* put_HsvColor)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
        struct __x_ABI_CXamlToolkit_CWinUI_CHsvColor value);
    HRESULT (STDMETHODCALLTYPE* get_IsAlphaMaxForced)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
        boolean* value);
    HRESULT (STDMETHODCALLTYPE* put_IsAlphaMaxForced)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
        boolean value);
    HRESULT (STDMETHODCALLTYPE* get_IsAutoUpdatingEnabled)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
        boolean* value);
    HRESULT (STDMETHODCALLTYPE* put_IsAutoUpdatingEnabled)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
        boolean value);
    HRESULT (STDMETHODCALLTYPE* get_IsSaturationValueMaxForced)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
        boolean* value);
    HRESULT (STDMETHODCALLTYPE* put_IsSaturationValueMaxForced)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
        boolean value);
    HRESULT (STDMETHODCALLTYPE* UpdateColors)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This);
    HRESULT (STDMETHODCALLTYPE* get_CheckerBackgroundColor)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
        struct __x_ABI_CWindows_CUI_CColor* value);
    HRESULT (STDMETHODCALLTYPE* put_CheckerBackgroundColor)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider* This,
        struct __x_ABI_CWindows_CUI_CColor value);

        END_INTERFACE
    } __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderVtbl;

    interface __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider
    {
        CONST_VTBL struct __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider;
#endif /* !defined(____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSlider_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics_INTERFACE_DEFINED__)
    #define ____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics_INTERFACE_DEFINED__
    typedef struct __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStaticsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_ColorProperty)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics* This,
        __x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty** value);
    HRESULT (STDMETHODCALLTYPE* get_ColorChannelProperty)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics* This,
        __x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty** value);
    HRESULT (STDMETHODCALLTYPE* get_ColorRepresentationProperty)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics* This,
        __x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty** value);
    HRESULT (STDMETHODCALLTYPE* get_DefaultForegroundProperty)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics* This,
        __x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty** value);
    HRESULT (STDMETHODCALLTYPE* get_HsvColorProperty)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics* This,
        __x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty** value);
    HRESULT (STDMETHODCALLTYPE* get_IsAlphaMaxForcedProperty)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics* This,
        __x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty** value);
    HRESULT (STDMETHODCALLTYPE* get_IsAutoUpdatingEnabledProperty)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics* This,
        __x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty** value);
    HRESULT (STDMETHODCALLTYPE* get_IsSaturationValueMaxForcedProperty)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics* This,
        __x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty** value);

        END_INTERFACE
    } __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStaticsVtbl;

    interface __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics
    {
        CONST_VTBL struct __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStaticsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics;
#endif /* !defined(____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPickerSliderStatics_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer_INTERFACE_DEFINED__)
    #define ____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer_INTERFACE_DEFINED__
    typedef struct __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_HsvColor)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer* This,
        struct __x_ABI_CXamlToolkit_CWinUI_CHsvColor* value);
    HRESULT (STDMETHODCALLTYPE* put_HsvColor)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer* This,
        struct __x_ABI_CXamlToolkit_CWinUI_CHsvColor value);
    HRESULT (STDMETHODCALLTYPE* get_ShowAccentColors)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer* This,
        boolean* value);
    HRESULT (STDMETHODCALLTYPE* put_ShowAccentColors)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer* This,
        boolean value);
    HRESULT (STDMETHODCALLTYPE* add_ColorChangeRequested)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer* This,
        __x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHsvColor* handler,
        EventRegistrationToken* token);
    HRESULT (STDMETHODCALLTYPE* remove_ColorChangeRequested)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer* This,
        EventRegistrationToken token);

        END_INTERFACE
    } __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerVtbl;

    interface __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer
    {
        CONST_VTBL struct __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer;
#endif /* !defined(____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewer_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerStatics_INTERFACE_DEFINED__)
    #define ____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerStatics_INTERFACE_DEFINED__
    typedef struct __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerStaticsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerStatics* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerStatics* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerStatics* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerStatics* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerStatics* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerStatics* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_HsvColorProperty)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerStatics* This,
        __x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty** value);
    HRESULT (STDMETHODCALLTYPE* get_ShowAccentColorsProperty)(__x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerStatics* This,
        __x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty** value);

        END_INTERFACE
    } __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerStaticsVtbl;

    interface __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerStatics
    {
        CONST_VTBL struct __x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerStaticsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerStatics;
#endif /* !defined(____x_ABI_CXamlToolkit_CWinUI_CControls_CPrimitives_CIColorPreviewerStatics_INTERFACE_DEFINED__) */
    
