// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"
#include "Microsoft.UI.Dispatching.h"
#include "Microsoft.UI.Xaml.h"
#include "Windows.Media.h"
#include "Windows.Media.Capture.Frames.h"
#include "Windows.UI.h"
#include "XamlToolkit.WinUI.h"
// Importing Collections header
#include "Windows.Foundation.Collections.h"

/* Forward Declarations */
#ifndef ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeChangedHandler_FWD_DEFINED__
#define ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeChangedHandler_FWD_DEFINED__
typedef interface __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeChangedHandler __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeChangedHandler;

#endif // ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeChangedHandler_FWD_DEFINED__

    #ifndef ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper_FWD_DEFINED__
#define ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper_FWD_DEFINED__
    typedef interface __x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper __x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper;

#endif // ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper_FWD_DEFINED__

#ifndef ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperStatics_FWD_DEFINED__
#define ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperStatics_FWD_DEFINED__
    typedef interface __x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperStatics __x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperStatics;

#endif // ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperStatics_FWD_DEFINED__

#ifndef ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelper_FWD_DEFINED__
#define ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelper_FWD_DEFINED__
    typedef interface __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelper __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelper;

#endif // ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelper_FWD_DEFINED__

#ifndef ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics_FWD_DEFINED__
#define ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics_FWD_DEFINED__
    typedef interface __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics;

#endif // ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics_FWD_DEFINED__

#ifndef ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpers_FWD_DEFINED__
#define ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpers_FWD_DEFINED__
    typedef interface __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpers __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpers;

#endif // ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpers_FWD_DEFINED__

#ifndef ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStatics_FWD_DEFINED__
#define ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStatics_FWD_DEFINED__
    typedef interface __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStatics __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStatics;

#endif // ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStatics_FWD_DEFINED__

#ifndef ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIFrameEventArgs_FWD_DEFINED__
#define ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIFrameEventArgs_FWD_DEFINED__
    typedef interface __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIFrameEventArgs __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIFrameEventArgs;

#endif // ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIFrameEventArgs_FWD_DEFINED__

#ifndef ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener_FWD_DEFINED__
#define ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener_FWD_DEFINED__
    typedef interface __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener;

#endif // ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener_FWD_DEFINED__

#ifndef ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerFactory_FWD_DEFINED__
#define ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerFactory_FWD_DEFINED__
    typedef interface __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerFactory __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerFactory;

#endif // ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerFactory_FWD_DEFINED__

// Parameterized interface forward declarations (C)

// Collection interface definitions

#ifndef ____x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameSourceGroup_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameSourceGroup_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameSourceGroup __x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameSourceGroup;

#endif // ____x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameSourceGroup_FWD_DEFINED__

#if !defined(____x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup __x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup;

    typedef struct __x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroupVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Current)(__x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
        __x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameSourceGroup** result);
    HRESULT (STDMETHODCALLTYPE* get_HasCurrent)(__x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* MoveNext)(__x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* GetMany)(__x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
        UINT32 itemsLength,
        __x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameSourceGroup** items,
        UINT32* result);

        END_INTERFACE
    } __x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroupVtbl;

    interface __x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup
    {
        CONST_VTBL struct __x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroupVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup __x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup;

    typedef struct __x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroupVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* First)(__x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
        __x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup** result);

        END_INTERFACE
    } __x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroupVtbl;

    interface __x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup
    {
        CONST_VTBL struct __x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroupVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup __x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup;

    typedef struct __x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroupVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* GetAt)(__x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
        UINT32 index,
        __x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameSourceGroup** result);
    HRESULT (STDMETHODCALLTYPE* get_Size)(__x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
        UINT32* result);
    HRESULT (STDMETHODCALLTYPE* IndexOf)(__x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
        __x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameSourceGroup* value,
        UINT32* index,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* GetMany)(__x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
        UINT32 startIndex,
        UINT32 itemsLength,
        __x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameSourceGroup** items,
        UINT32* result);

        END_INTERFACE
    } __x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroupVtbl;

    interface __x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup
    {
        CONST_VTBL struct __x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroupVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup_INTERFACE_DEFINED__
    
typedef interface __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup;

#if !defined(____x_ABI_C__FIAsyncOperation_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperation_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperation_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup __x_ABI_C__FIAsyncOperation_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperation_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup;

    typedef struct __x_ABI_C__FIAsyncOperation_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroupVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperation_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperation_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperation_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIAsyncOperation_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIAsyncOperation_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIAsyncOperation_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* put_Completed)(__x_ABI_C__FIAsyncOperation_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
        __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* handler);
    HRESULT (STDMETHODCALLTYPE* get_Completed)(__x_ABI_C__FIAsyncOperation_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
        __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup** result);
    HRESULT (STDMETHODCALLTYPE* GetResults)(__x_ABI_C__FIAsyncOperation_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
        __x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup** result);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperation_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroupVtbl;

    interface __x_ABI_C__FIAsyncOperation_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperation_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroupVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperation_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup;

    typedef struct __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroupVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* This,
        __x_ABI_C__FIAsyncOperation_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup* asyncInfo,
        enum __x_ABI_CWindows_CFoundation_CAsyncStatus asyncStatus);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroupVtbl;

    interface __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroupVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup_INTERFACE_DEFINED__
    
typedef enum __x_ABI_CXamlToolkit_CWinUI_CHelpers_CCameraHelperResult __x_ABI_CXamlToolkit_CWinUI_CHelpers_CCameraHelperResult;

typedef interface __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult;

#if !defined(____x_ABI_C__FIAsyncOperation_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperation_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperation_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult __x_ABI_C__FIAsyncOperation_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperation_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult;

    typedef struct __x_ABI_C__FIAsyncOperation_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResultVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* put_Completed)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult* This,
        __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult* handler);
    HRESULT (STDMETHODCALLTYPE* get_Completed)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult* This,
        __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult** result);
    HRESULT (STDMETHODCALLTYPE* GetResults)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult* This,
        enum __x_ABI_CXamlToolkit_CWinUI_CHelpers_CCameraHelperResult* result);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperation_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResultVtbl;

    interface __x_ABI_C__FIAsyncOperation_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperation_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResultVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperation_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult;

    typedef struct __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResultVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult* This,
        __x_ABI_C__FIAsyncOperation_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult* asyncInfo,
        enum __x_ABI_CWindows_CFoundation_CAsyncStatus asyncStatus);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResultVtbl;

    interface __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResultVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult_INTERFACE_DEFINED__
    
#ifndef ____x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameFormat_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameFormat_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameFormat __x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameFormat;

#endif // ____x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameFormat_FWD_DEFINED__

#if !defined(____x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat __x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat;

    typedef struct __x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormatVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Current)(__x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This,
        __x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameFormat** result);
    HRESULT (STDMETHODCALLTYPE* get_HasCurrent)(__x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* MoveNext)(__x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* GetMany)(__x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This,
        UINT32 itemsLength,
        __x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameFormat** items,
        UINT32* result);

        END_INTERFACE
    } __x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormatVtbl;

    interface __x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat
    {
        CONST_VTBL struct __x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormatVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat __x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat;

    typedef struct __x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormatVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* First)(__x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This,
        __x_ABI_C__FIIterator_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat** result);

        END_INTERFACE
    } __x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormatVtbl;

    interface __x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat
    {
        CONST_VTBL struct __x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormatVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIIterable_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat __x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat;

    typedef struct __x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormatVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* GetAt)(__x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This,
        UINT32 index,
        __x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameFormat** result);
    HRESULT (STDMETHODCALLTYPE* get_Size)(__x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This,
        UINT32* result);
    HRESULT (STDMETHODCALLTYPE* IndexOf)(__x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This,
        __x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameFormat* value,
        UINT32* index,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* GetMany)(__x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat* This,
        UINT32 startIndex,
        UINT32 itemsLength,
        __x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameFormat** items,
        UINT32* result);

        END_INTERFACE
    } __x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormatVtbl;

    interface __x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat
    {
        CONST_VTBL struct __x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormatVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CFrameEventArgs_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CFrameEventArgs_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CFrameEventArgs __x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CFrameEventArgs;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CFrameEventArgs;

    typedef struct __x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CFrameEventArgsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CFrameEventArgs* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CFrameEventArgs* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CFrameEventArgs* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CFrameEventArgs* This,
        IInspectable* sender,
        __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIFrameEventArgs* args);

        END_INTERFACE
    } __x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CFrameEventArgsVtbl;

    interface __x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CFrameEventArgs
    {
        CONST_VTBL struct __x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CFrameEventArgsVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CFrameEventArgs_INTERFACE_DEFINED__
    
#ifndef ____x_ABI_CMicrosoft_CUI_CDispatching_CIDispatcherQueue_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CDispatching_CIDispatcherQueue_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CDispatching_CIDispatcherQueue __x_ABI_CMicrosoft_CUI_CDispatching_CIDispatcherQueue;

#endif // ____x_ABI_CMicrosoft_CUI_CDispatching_CIDispatcherQueue_FWD_DEFINED__

typedef enum __x_ABI_CMicrosoft_CUI_CXaml_CApplicationTheme __x_ABI_CMicrosoft_CUI_CXaml_CApplicationTheme;

typedef enum __x_ABI_CWindows_CFoundation_CAsyncStatus __x_ABI_CWindows_CFoundation_CAsyncStatus;

#ifndef ____x_ABI_CWindows_CFoundation_CIAsyncAction_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIAsyncAction_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIAsyncAction __x_ABI_CWindows_CFoundation_CIAsyncAction;

#endif // ____x_ABI_CWindows_CFoundation_CIAsyncAction_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CFoundation_CIAsyncInfo_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIAsyncInfo_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIAsyncInfo __x_ABI_CWindows_CFoundation_CIAsyncInfo;

#endif // ____x_ABI_CWindows_CFoundation_CIAsyncInfo_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIClosable __x_ABI_CWindows_CFoundation_CIClosable;

#endif // ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameSource_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameSource_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameSource __x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameSource;

#endif // ____x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameSource_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CMedia_CIVideoFrame_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CIVideoFrame_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CMedia_CIVideoFrame __x_ABI_CWindows_CMedia_CIVideoFrame;

#endif // ____x_ABI_CWindows_CMedia_CIVideoFrame_FWD_DEFINED__

typedef struct __x_ABI_CWindows_CUI_CColor __x_ABI_CWindows_CUI_CColor;

typedef struct __x_ABI_CXamlToolkit_CWinUI_CHslColor __x_ABI_CXamlToolkit_CWinUI_CHslColor;

typedef struct __x_ABI_CXamlToolkit_CWinUI_CHsvColor __x_ABI_CXamlToolkit_CWinUI_CHsvColor;

enum __x_ABI_CXamlToolkit_CWinUI_CHelpers_CCameraHelperResult
    {
        __x_ABI_CXamlToolkit_CWinUI_CHelpers_CCameraHelperResult_Success = 0,
    __x_ABI_CXamlToolkit_CWinUI_CHelpers_CCameraHelperResult_CreateFrameReaderFailed = 1,
    __x_ABI_CXamlToolkit_CWinUI_CHelpers_CCameraHelperResult_StartFrameReaderFailed = 2,
    __x_ABI_CXamlToolkit_CWinUI_CHelpers_CCameraHelperResult_NoFrameSourceGroupAvailable = 3,
    __x_ABI_CXamlToolkit_CWinUI_CHelpers_CCameraHelperResult_NoFrameSourceAvailable = 4,
    __x_ABI_CXamlToolkit_CWinUI_CHelpers_CCameraHelperResult_CameraAccessDenied = 5,
    __x_ABI_CXamlToolkit_CWinUI_CHelpers_CCameraHelperResult_InitializationFailed_UnknownError = 6,
    __x_ABI_CXamlToolkit_CWinUI_CHelpers_CCameraHelperResult_NoCompatibleFrameFormatAvailable = 7,
};

#if !defined(____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeChangedHandler_INTERFACE_DEFINED__)
    #define ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeChangedHandler_INTERFACE_DEFINED__
    typedef struct __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeChangedHandlerVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeChangedHandler* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeChangedHandler* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeChangedHandler* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeChangedHandler* This,
        __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener* sender);

        END_INTERFACE
    } __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeChangedHandlerVtbl;

    interface __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeChangedHandler
    {
        CONST_VTBL struct __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeChangedHandlerVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeChangedHandler;
    #endif /* !defined(____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeChangedHandler_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper_INTERFACE_DEFINED__)
    #define ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper_INTERFACE_DEFINED__
    typedef struct __x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_FrameSourceGroup)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper* This,
        __x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameSourceGroup** value);
    HRESULT (STDMETHODCALLTYPE* put_FrameSourceGroup)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper* This,
        __x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameSourceGroup* value);
    HRESULT (STDMETHODCALLTYPE* get_FrameFormatsAvailable)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper* This,
        __x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameFormat** value);
    HRESULT (STDMETHODCALLTYPE* get_PreviewFrameSource)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper* This,
        __x_ABI_CWindows_CMedia_CCapture_CFrames_CIMediaFrameSource** value);
    HRESULT (STDMETHODCALLTYPE* add_FrameArrived)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper* This,
        __x_ABI_C__FIEventHandler_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CFrameEventArgs* handler,
        EventRegistrationToken* token);
    HRESULT (STDMETHODCALLTYPE* remove_FrameArrived)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper* This,
        EventRegistrationToken token);
    HRESULT (STDMETHODCALLTYPE* InitializeAndStartCaptureAsync)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper* This,
        __x_ABI_C__FIAsyncOperation_1___x_ABI_CXamlToolkit__CWinUI__CHelpers__CCameraHelperResult** operation);
    HRESULT (STDMETHODCALLTYPE* CleanUpAsync)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper* This,
        __x_ABI_CWindows_CFoundation_CIAsyncAction** operation);

        END_INTERFACE
    } __x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperVtbl;

    interface __x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper
    {
        CONST_VTBL struct __x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper;
#endif /* !defined(____x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelper_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperStatics_INTERFACE_DEFINED__)
    #define ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperStatics_INTERFACE_DEFINED__
    typedef struct __x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperStaticsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperStatics* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperStatics* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperStatics* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperStatics* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperStatics* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperStatics* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* GetFrameSourceGroupsAsync)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperStatics* This,
        __x_ABI_C__FIAsyncOperation_1___x_ABI_C__FIVectorView_1___x_ABI_CWindows__CMedia__CCapture__CFrames__CMediaFrameSourceGroup** operation);

        END_INTERFACE
    } __x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperStaticsVtbl;

    interface __x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperStatics
    {
        CONST_VTBL struct __x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperStaticsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperStatics;
#endif /* !defined(____x_ABI_CXamlToolkit_CWinUI_CHelpers_CICameraHelperStatics_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelper_INTERFACE_DEFINED__)
    #define ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelper_INTERFACE_DEFINED__
    typedef struct __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelper* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelper* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelper* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelper* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelper* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelper* This,
            TrustLevel* trustLevel);
    
        END_INTERFACE
    } __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperVtbl;

    interface __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelper
    {
        CONST_VTBL struct __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelper;
#endif /* !defined(____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelper_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics_INTERFACE_DEFINED__)
    #define ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics_INTERFACE_DEFINED__
    typedef struct __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStaticsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* ToColor)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics* This,
        HSTRING colorString,
        struct __x_ABI_CWindows_CUI_CColor* result);
    HRESULT (STDMETHODCALLTYPE* ToHex)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics* This,
        struct __x_ABI_CWindows_CUI_CColor color,
        HSTRING* result);
    HRESULT (STDMETHODCALLTYPE* ToHsl)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics* This,
        struct __x_ABI_CWindows_CUI_CColor color,
        struct __x_ABI_CXamlToolkit_CWinUI_CHslColor* result);
    HRESULT (STDMETHODCALLTYPE* ToHsv)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics* This,
        struct __x_ABI_CWindows_CUI_CColor color,
        struct __x_ABI_CXamlToolkit_CWinUI_CHsvColor* result);
    HRESULT (STDMETHODCALLTYPE* FromHsl)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics* This,
        DOUBLE hue,
        DOUBLE saturation,
        DOUBLE lightness,
        DOUBLE alpha,
        struct __x_ABI_CWindows_CUI_CColor* result);
    HRESULT (STDMETHODCALLTYPE* FromHsv)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics* This,
        DOUBLE hue,
        DOUBLE saturation,
        DOUBLE value,
        DOUBLE alpha,
        struct __x_ABI_CWindows_CUI_CColor* result);

        END_INTERFACE
    } __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStaticsVtbl;

    interface __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics
    {
        CONST_VTBL struct __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStaticsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics;
#endif /* !defined(____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIColorHelperStatics_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpers_INTERFACE_DEFINED__)
    #define ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpers_INTERFACE_DEFINED__
    typedef struct __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpers* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpers* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpers* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpers* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpers* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpers* This,
            TrustLevel* trustLevel);
    
        END_INTERFACE
    } __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersVtbl;

    interface __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpers
    {
        CONST_VTBL struct __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpers;
#endif /* !defined(____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpers_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStatics_INTERFACE_DEFINED__)
    #define ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStatics_INTERFACE_DEFINED__
    typedef struct __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStaticsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStatics* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStatics* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStatics* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStatics* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStatics* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStatics* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* IsRunningInLegacyDesignerMode)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStatics* This,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* IsRunningInEnhancedDesignerMode)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStatics* This,
        boolean* result);
    HRESULT (STDMETHODCALLTYPE* IsRunningInApplicationRuntimeMode)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStatics* This,
        boolean* result);

        END_INTERFACE
    } __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStaticsVtbl;

    interface __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStatics
    {
        CONST_VTBL struct __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStaticsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStatics;
#endif /* !defined(____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIDesignTimeHelpersStatics_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIFrameEventArgs_INTERFACE_DEFINED__)
    #define ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIFrameEventArgs_INTERFACE_DEFINED__
    typedef struct __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIFrameEventArgsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIFrameEventArgs* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIFrameEventArgs* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIFrameEventArgs* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIFrameEventArgs* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIFrameEventArgs* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIFrameEventArgs* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_VideoFrame)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIFrameEventArgs* This,
        __x_ABI_CWindows_CMedia_CIVideoFrame** value);

        END_INTERFACE
    } __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIFrameEventArgsVtbl;

    interface __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIFrameEventArgs
    {
        CONST_VTBL struct __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIFrameEventArgsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CXamlToolkit_CWinUI_CHelpers_CIFrameEventArgs;
#endif /* !defined(____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIFrameEventArgs_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener_INTERFACE_DEFINED__)
    #define ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener_INTERFACE_DEFINED__
    typedef struct __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_CurrentTheme)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener* This,
        enum __x_ABI_CMicrosoft_CUI_CXaml_CApplicationTheme* value);
    HRESULT (STDMETHODCALLTYPE* get_CurrentThemeName)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_IsHighContrast)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener* This,
        boolean* value);
    HRESULT (STDMETHODCALLTYPE* add_ThemeChanged)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener* This,
        __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeChangedHandler* handler,
        EventRegistrationToken* token);
    HRESULT (STDMETHODCALLTYPE* remove_ThemeChanged)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener* This,
        EventRegistrationToken token);

        END_INTERFACE
    } __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerVtbl;

    interface __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener
    {
        CONST_VTBL struct __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener;
#endif /* !defined(____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerFactory_INTERFACE_DEFINED__)
    #define ____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerFactory_INTERFACE_DEFINED__
    typedef struct __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerFactoryVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerFactory* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerFactory* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerFactory* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerFactory* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerFactory* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerFactory* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateInstance)(__x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerFactory* This,
        __x_ABI_CMicrosoft_CUI_CDispatching_CIDispatcherQueue* dispatcherQueue,
        __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListener** value);

        END_INTERFACE
    } __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerFactoryVtbl;

    interface __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerFactory
    {
        CONST_VTBL struct __x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerFactoryVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerFactory;
#endif /* !defined(____x_ABI_CXamlToolkit_CWinUI_CHelpers_CIThemeListenerFactory_INTERFACE_DEFINED__) */
    
