// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"
#include "Microsoft.UI.Xaml.h"
#include "Microsoft.UI.Xaml.Data.h"

/* Forward Declarations */
#ifndef ____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverter_FWD_DEFINED__
#define ____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverter_FWD_DEFINED__
    typedef interface __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverter __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverter;

#endif // ____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverter_FWD_DEFINED__

#ifndef ____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterFactory_FWD_DEFINED__
#define ____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterFactory_FWD_DEFINED__
    typedef interface __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterFactory __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterFactory;

#endif // ____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterFactory_FWD_DEFINED__

#ifndef ____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterStatics_FWD_DEFINED__
#define ____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterStatics_FWD_DEFINED__
    typedef interface __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterStatics __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterStatics;

#endif // ____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterStatics_FWD_DEFINED__

#ifndef ____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToVisibilityConverter_FWD_DEFINED__
#define ____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToVisibilityConverter_FWD_DEFINED__
    typedef interface __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToVisibilityConverter __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToVisibilityConverter;

#endif // ____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToVisibilityConverter_FWD_DEFINED__

#ifndef ____x_ABI_CXamlToolkit_CWinUI_CConverters_CIColorToDisplayNameConverter_FWD_DEFINED__
#define ____x_ABI_CXamlToolkit_CWinUI_CConverters_CIColorToDisplayNameConverter_FWD_DEFINED__
    typedef interface __x_ABI_CXamlToolkit_CWinUI_CConverters_CIColorToDisplayNameConverter __x_ABI_CXamlToolkit_CWinUI_CConverters_CIColorToDisplayNameConverter;

#endif // ____x_ABI_CXamlToolkit_CWinUI_CConverters_CIColorToDisplayNameConverter_FWD_DEFINED__

// Parameterized interface forward declarations (C)

// Collection interface definitions

#ifndef ____x_ABI_CMicrosoft_CUI_CXaml_CData_CIValueConverter_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CXaml_CData_CIValueConverter_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CXaml_CData_CIValueConverter __x_ABI_CMicrosoft_CUI_CXaml_CData_CIValueConverter;

#endif // ____x_ABI_CMicrosoft_CUI_CXaml_CData_CIValueConverter_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty __x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty;

#endif // ____x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CUI_CXaml_CIDependencyObject_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CUI_CXaml_CIDependencyObject_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CUI_CXaml_CIDependencyObject __x_ABI_CMicrosoft_CUI_CXaml_CIDependencyObject;

#endif // ____x_ABI_CMicrosoft_CUI_CXaml_CIDependencyObject_FWD_DEFINED__

#if !defined(____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverter_INTERFACE_DEFINED__)
    #define ____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverter_INTERFACE_DEFINED__
    typedef struct __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverter* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverter* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverter* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverter* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverter* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverter* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_TrueValue)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverter* This,
        IInspectable** value);
    HRESULT (STDMETHODCALLTYPE* put_TrueValue)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverter* This,
        IInspectable* value);
    HRESULT (STDMETHODCALLTYPE* get_FalseValue)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverter* This,
        IInspectable** value);
    HRESULT (STDMETHODCALLTYPE* put_FalseValue)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverter* This,
        IInspectable* value);

        END_INTERFACE
    } __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterVtbl;

    interface __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverter
    {
        CONST_VTBL struct __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverter;
#endif /* !defined(____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverter_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterFactory_INTERFACE_DEFINED__)
    #define ____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterFactory_INTERFACE_DEFINED__
    typedef struct __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterFactoryVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterFactory* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterFactory* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterFactory* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterFactory* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterFactory* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterFactory* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateInstance)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterFactory* This,
        IInspectable* baseInterface,
        IInspectable** innerInterface,
        __x_ABI_CMicrosoft_CUI_CXaml_CData_CIValueConverter** value);

        END_INTERFACE
    } __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterFactoryVtbl;

    interface __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterFactory
    {
        CONST_VTBL struct __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterFactoryVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterFactory;
#endif /* !defined(____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterFactory_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterStatics_INTERFACE_DEFINED__)
    #define ____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterStatics_INTERFACE_DEFINED__
    typedef struct __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterStaticsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterStatics* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterStatics* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterStatics* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterStatics* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterStatics* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterStatics* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_TrueValueProperty)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterStatics* This,
        __x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty** value);
    HRESULT (STDMETHODCALLTYPE* get_FalseValueProperty)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterStatics* This,
        __x_ABI_CMicrosoft_CUI_CXaml_CIDependencyProperty** value);

        END_INTERFACE
    } __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterStaticsVtbl;

    interface __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterStatics
    {
        CONST_VTBL struct __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterStaticsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterStatics;
#endif /* !defined(____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToObjectConverterStatics_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToVisibilityConverter_INTERFACE_DEFINED__)
    #define ____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToVisibilityConverter_INTERFACE_DEFINED__
    typedef struct __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToVisibilityConverterVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToVisibilityConverter* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToVisibilityConverter* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToVisibilityConverter* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToVisibilityConverter* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToVisibilityConverter* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToVisibilityConverter* This,
            TrustLevel* trustLevel);
    
        END_INTERFACE
    } __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToVisibilityConverterVtbl;

    interface __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToVisibilityConverter
    {
        CONST_VTBL struct __x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToVisibilityConverterVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToVisibilityConverter;
#endif /* !defined(____x_ABI_CXamlToolkit_CWinUI_CConverters_CIBoolToVisibilityConverter_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CXamlToolkit_CWinUI_CConverters_CIColorToDisplayNameConverter_INTERFACE_DEFINED__)
    #define ____x_ABI_CXamlToolkit_CWinUI_CConverters_CIColorToDisplayNameConverter_INTERFACE_DEFINED__
    typedef struct __x_ABI_CXamlToolkit_CWinUI_CConverters_CIColorToDisplayNameConverterVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIColorToDisplayNameConverter* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIColorToDisplayNameConverter* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIColorToDisplayNameConverter* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIColorToDisplayNameConverter* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIColorToDisplayNameConverter* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CXamlToolkit_CWinUI_CConverters_CIColorToDisplayNameConverter* This,
            TrustLevel* trustLevel);
    
        END_INTERFACE
    } __x_ABI_CXamlToolkit_CWinUI_CConverters_CIColorToDisplayNameConverterVtbl;

    interface __x_ABI_CXamlToolkit_CWinUI_CConverters_CIColorToDisplayNameConverter
    {
        CONST_VTBL struct __x_ABI_CXamlToolkit_CWinUI_CConverters_CIColorToDisplayNameConverterVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CXamlToolkit_CWinUI_CConverters_CIColorToDisplayNameConverter;
#endif /* !defined(____x_ABI_CXamlToolkit_CWinUI_CConverters_CIColorToDisplayNameConverter_INTERFACE_DEFINED__) */
    
